create table if not exists account
(
    balance_cash numeric(12, 2) not null,
    balance_food numeric(12, 2) not null,
    balance_meal numeric(12, 2) not null,
    id           bigint generated by default as identity primary key
);

create table if not exists mcc
(
    mcc          varchar(4) not null unique,
    id           bigint generated by default as identity primary key,
    balance_type varchar(255)
        constraint mcc_balance_type_check
            check ((balance_type)::text = ANY
                   ((ARRAY ['FOOD'::character varying, 'MEAL'::character varying, 'CASH'::character varying])::text[]))
);

create table if not exists merchant
(
    id     bigint generated by default as identity primary key,
    mcc_id bigint       not null
        constraint fksl64748r1c7jxlqr66uamhi8o references mcc,
    name   varchar(255) not null
);

create table if not exists transaction
(
    id                       bigint generated by default as identity primary key,
    amount                   numeric(10, 2) not null,
    account_id               bigint         not null
        constraint fk6g20fcr3bhr6bihgy24rq1r1b
            references account,
    merchant_id              bigint         not null
        constraint fkcwlugq1eich0rct1w83pewkqc
            references merchant,
    mcc                      varchar(255)   not null,
    transaction_balance_type varchar(255)
        constraint transaction_transaction_balance_type_check
            check ((transaction_balance_type)::text = ANY
                   ((ARRAY ['FOOD'::character varying, 'MEAL'::character varying, 'CASH'::character varying])::text[]))
);

